# Generated by Django 5.1.5 on 2025-01-27 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
