# Generated by Django 5.1.5 on 2025-01-27 18:30

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produs', '0002_comanda'),
    ]

    operations = [
        migrations.AddField(
            model_name='comanda',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='produs.client'),
        ),
        migrations.AddField(
            model_name='comanda',
            name='data_creare',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 27, 18, 30, 23, 920428, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='comanda',
            name='produse',
            field=models.ManyToManyField(to='produs.produs'),
        ),
        migrations.AddField(
            model_name='comanda',
            name='status',
            field=models.CharField(choices=[('in asteptare', 'În așteptare'), ('procesata', 'Procesată'), ('livrata', 'Livrată'), ('anulata', 'Anulată')], default='in asteptare', max_length=20),
        ),
    ]
