# Generated by Django 4.2 on 2025-01-28 19:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produs', '0006_alter_comanda_data_creare_cerereprodus'),
    ]

    operations = [
        migrations.AddField(
            model_name='produs',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='produse', to='produs.category'),
        ),
        migrations.AlterField(
            model_name='comanda',
            name='data_creare',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 28, 21, 54, 12, 454345)),
        ),
        migrations.DeleteModel(
            name='CerereProdus',
        ),
    ]
