# Generated by Django 4.2 on 2025-01-29 16:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produs', '0007_produs_category_alter_comanda_data_creare_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produs',
            name='imagine',
            field=models.ImageField(blank=True, null=True, upload_to='produse/'),
        ),
        migrations.AlterField(
            model_name='comanda',
            name='data_creare',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 29, 18, 59, 15, 405040)),
        ),
    ]
