# Generated by Django 4.2 on 2025-01-29 18:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produs', '0008_produs_imagine_alter_comanda_data_creare'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='comanda',
            name='data_creare',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 29, 20, 50, 26, 87241)),
        ),
    ]
