# Generated by Django 4.2 on 2025-02-03 18:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produs', '0010_alter_client_password_alter_comanda_data_creare'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='password',
        ),
        migrations.AlterField(
            model_name='comanda',
            name='data_creare',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 3, 20, 51, 20, 880984)),
        ),
    ]
