# Generated by Django 4.2 on 2025-02-03 19:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produs', '0012_alter_comanda_data_creare'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comanda',
            name='data_creare',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 3, 21, 39, 48, 556510)),
        ),
    ]
