# Generated by Django 4.2 on 2025-02-05 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produs', '0014_alter_comanda_data_creare'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comanda',
            name='client',
        ),
        migrations.RemoveField(
            model_name='comanda',
            name='produse',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Comanda',
        ),
    ]
