# Generated by Django 4.2 on 2025-02-05 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produs', '0016_imaginiprodus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imaginiprodus',
            name='imagine',
            field=models.ImageField(blank=True, null=True, upload_to='produse_imagini_suplimentare'),
        ),
    ]
