# Generated by Django 4.2 on 2025-02-05 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produs', '0018_alter_imaginiprodus_imagine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imaginiprodus',
            name='imagine',
            field=models.ImageField(default='media/produse_imagini_suplimentare', upload_to='produse_imagini'),
        ),
    ]
