# Generated by Django 4.2 on 2025-02-06 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produs', '0019_alter_imaginiprodus_imagine'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='description',
            new_name='descriere',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='nume',
        ),
        migrations.CreateModel(
            name='Subcategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=100)),
                ('descriere', models.TextField(blank=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategorie', to='produs.category')),
            ],
        ),
        migrations.AddField(
            model_name='produs',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produse', to='produs.subcategorie'),
        ),
    ]
