# Generated by Django 4.2 on 2025-02-06 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produs', '0020_rename_description_category_descriere_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategorie',
            name='descriere',
        ),
        migrations.AlterField(
            model_name='subcategorie',
            name='categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produs.category'),
        ),
    ]
