# Generated by Django 4.2 on 2025-02-06 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produs', '0021_remove_subcategorie_descriere_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produs',
            name='subcategory',
        ),
        migrations.DeleteModel(
            name='Subcategorie',
        ),
    ]
