# Generated by Django 4.2 on 2025-02-10 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produs', '0023_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imaginiprodus',
            name='imagine',
            field=models.ImageField(upload_to='produse_imagini'),
        ),
    ]
