# Generated by Django 4.2 on 2025-02-12 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produs', '0024_alter_imaginiprodus_imagine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produs',
            name='descriere',
            field=models.TextField(blank=True, null=True),
        ),
    ]
