# Generated by Django 4.2 on 2025-02-12 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produs', '0026_contactmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='data',
        ),
    ]
