# Generated by Django 4.2 on 2025-02-13 17:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('produs', '0027_remove_contactmessage_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_creare', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'În așteptare'), ('Processing', 'În procesare'), ('Shipped', 'Expediată'), ('Delivered', 'Livrată'), ('Cancelled', 'Anulată')], default='Pending', max_length=20)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='ComandaFinala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantitate', models.PositiveIntegerField(default=1)),
                ('pret_unitar', models.DecimalField(decimal_places=2, max_digits=6)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produs.comanda')),
                ('produs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produs.produs')),
            ],
        ),
        migrations.AddField(
            model_name='comanda',
            name='produse',
            field=models.ManyToManyField(through='produs.ComandaFinala', to='produs.produs'),
        ),
        migrations.AddField(
            model_name='comanda',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CosCumparaturi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantitate', models.PositiveIntegerField(default=1)),
                ('produs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produs.produs')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'produs')},
            },
        ),
    ]
