# Generated by Django 4.2 on 2025-02-13 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produs', '0028_comanda_comandafinala_comanda_produse_comanda_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comandafinala',
            old_name='order',
            new_name='comanda',
        ),
    ]
